# wrangler.toml

name = "dori-ai-prod"
main = ".open-next/server/index.js"
compatibility_date = "2024-05-18"

[site]
bucket = ".open-next/assets"

[vars]
# Add your environment variables here
# EXAMPLE_VAR = "example_value"

[[migrations]]
tag = "v1"
new_classes = ["Everyone"]
